export const START_LOADER = 'START_LOADER';
export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const DISPLAY_ERROR_MSG = 'DISPLAY_ERROR_MSG';